swagger: '2.0'
info:
  title: Physiotherapy API
  description: API for physiotherapy services
  version: '1.0'
host: physiotherapy-api-europe-central2.gateway.dev
schemes:
  - https
paths:
  /api/users/**:
    get:
      summary: Get user details
      operationId: getUsers
      produces:
        - application/json
      responses:
        200:
          description: Successful response
      x-google-backend:
        address: https://USER_SERVICE_IP.nip.io/api/users

  /api/appointments/**:
    get:
      summary: Get appointment details
      operationId: getAppointments
      produces:
        - application/json
      responses:
        200:
          description: Successful response
      x-google-backend:
        address: https://APPOINTMENT_SERVICE_IP.nip.io/api/appointments

  /api/tokens/**:
    get:
      summary: Get token details
      operationId: getTokens
      produces:
        - application/json
      responses:
        200:
          description: Successful response
      x-google-backend:
        address: https://TOKEN_SERVICE_IP.nip.io/api/tokens
