apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: gcr.io/physiotherapy-clinic-431211/appointment-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://google/clinic_database?cloudSqlInstance=physiotherapy-clinic-431211:europe-central2:my-postgresql-instance&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=clinic_user&password=clinic_user123"
        - name: SPRING_DATASOURCE_USERNAME
          value: "clinic_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "clinic_user123"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
