name: Continuous Sync from DevOpsProject to Clinic-token-system

on:
  schedule:
    # Runs at midnight every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the SampleProjects repository (this repository) on the main branch
    - name: Checkout Target Repo (SampleProjects)
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: main

    # Step 2: Check if Clinic-token-system is a submodule and remove it
    - name: Remove Submodule Configuration (if exists)
      run: |
        if git config --file .gitmodules --get-regexp path | grep 'Clinic-token-system'; then
          echo "Submodule detected. Removing submodule."
          git submodule deinit -f Clinic-token-system || true
          git rm -f Clinic-token-system || true
          rm -rf .git/modules/Clinic-token-system || true
          rm -rf Clinic-token-system || true
          if [ -f ".gitmodules" ]; then
            echo "Removing reference from .gitmodules..."
            sed -i '/Clinic-token-system/d' .gitmodules
            git add .gitmodules
          fi
          git commit -m "Remove submodule Clinic-token-system and clean up"
        else
          echo "No submodule detected."
        fi

    # Step 3: Pull the latest changes from the main branch of SampleProjects
    - name: Pull Latest Changes from Main Branch
      run: |
        git pull origin main

    # Step 4: Authenticate using the PAT for fetching from DevOpsProject
    - name: Set up Authentication
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote add source https://${{ secrets.GH_PAT }}@github.com/ashiksp1994/DevOpsProject.git

    # Step 5: Fetch and sync DevOpsProject to the Clinic-token-system folder
    - name: Fetch and Sync DevOpsProject Repo
      run: |
        # Fetch the latest changes from DevOpsProject
        git fetch source
        git checkout source/main -- .

        # Ensure the Clinic-token-system folder exists
        mkdir -p Clinic-token-system

        # Rsync the contents of DevOpsProject to Clinic-token-system folder in SampleProjects
        rsync -av --delete --progress --exclude ".git" ./ Clinic-token-system/

    # Step 6: Commit any changes if found
    - name: Commit Changes
      run: |
        git add Clinic-token-system/
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Sync files from DevOpsProject to Clinic-token-system"
        fi

    # Step 7: Push changes to the main branch
    - name: Push Changes to Main Branch
      env:
        GH_PAT: ${{ secrets.GH_PAT }} # Use PAT for authentication
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/ashiksp1994/SampleProjects.git main || echo "No changes to push"
